version: '2'
services:
  01pw:
    build: ..
    ports:
      - "8081:8080"
    volumes:
      - ../example.json:/srv/vault/example.json
  nginx:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

